- hosts: localhost
  vars_files:
    - [ "vars/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml",
        "vars/{{ansible_distribution}}.yml" ]
  tasks:
    - name: configure delorean repository
      get_url: 
        url: "{{item}}"
        dest: /etc/yum.repos.d/
      with_items: delorean_repo_urls

    - name: install packages
      action: "{{packager}}"
      args:
        name: "{{item}}"
        state: latest
      with_items:
        - openvswitch
        - rabbitmq-server
        - openstack-neutron
        - openstack-neutron-ml2
        - openstack-neutron-lbaas
        - openstack-neutron-openvswitch

    - name: enable services
      command: systemctl enable {{item}}
      with_items:
        - openvswitch
        - rabbitmq-server
        - neutron-server
        - neutron-dhcp-agent
        - neutron-l3-agent
        - neutron-openvswitch-agent
        - neutron-lbaas-agent

    - name: configure neutron DEFAULT
      ini_file:
        dest: /etc/neutron/neutron.conf
        section: DEFAULT
        option: "{{item.option}}"
        value: "{{item.value}}"
      with_items:
        - option: verbose
          value: True
        - option: core_plugin
          value: ml2
        - option: service_plugins
          value: router,lbaas
        - option: auth_strategy
          value: noauth
        - option: rabbit_host
          value: localhost

    - name: configure neutron ml2
      ini_file:
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        section: ml2
        option: "{{item.option}}"
        value: "{{item.value}}"
      with_items:
        - option: type_drivers
          value: flat,vxlan
        - option: tenant_network_types
          value: vxlan
        - option: mechanism_drivers
          value: openvswitch

    - name: symlink plugin configuration
      file:
        state: link
        src: /etc/neutron/plugins/ml2/ml2_conf.ini
        dest: /etc/neutron/plugin.ini
