- hosts: localhost
  tasks:
    - get_url: 
        url: http://trunk.rdoproject.org/f21/current/delorean.repo
        dest: /etc/yum.repos.d/delorean.repo

    - dnf:
        name: "{{item}}"
        state: latest
      with_items:
        - openstack-neutron
        - openstack-neutron-ml2
        - openstack-neutron-openvswitch

    - command: systemctl enable {{item}}
      with_items:
        - neutron-server
        - neutron-dhcp-agent
        - neutron-l3-agent
        - neutron-openvswitch-agent
        - neutron-lbaas-agent
